import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../src/components/Navbar';

const Marketplace: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RentX NFT</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

     
    </div>
  );
};

export default Marketplace;
